name = "AdvPlots"
uuid = "4b07f121-2307-42c0-8344-6814ace90e04"
version = "0.1.0"
authors = ["You <you@example.com>"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MathTeXEngine = "0a4f8689-d25c-4efe-a92b-7142dfc1aa53"
Statistics = "10745b16-94df-5e57-8adb-5f3dc4aa0c3f"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CairoMakie = "0.15.7"
Distributions = "0.25.122"
LaTeXStrings = "1.4.0"
MathTeXEngine = "0.6.7"
StatsBase = "0.34.8"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
